#!/usr/bin/env python3
"""Generate deterministic Rust bindings for component-release/v1."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


REQUIRED = ("agent-contracts", "code", "loop-hub", "runtime")


def canonical_json(path: Path) -> bytes:
    value = json.loads(path.read_text(encoding="utf-8"))
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def render(schema: Path) -> str:
    document = json.loads(schema.read_text(encoding="utf-8"))
    if document.get("properties", {}).get("schema", {}).get("const") != "simplicio.component-release/v1":
        raise ValueError("schema does not describe component-release/v1")
    required = set(document.get("properties", {}).get("components", {}).get("items", {}).get("required", ()))
    if required != {"name", "version", "commit", "protocol", "artifact_digest"}:
        raise ValueError("component schema required fields changed; review the generated binding")
    digest = hashlib.sha256(canonical_json(schema)).hexdigest()
    return f'''//! DO NOT EDIT: generated by `scripts/release/generate_component_client.py`.
//!
//! Regenerate this file from the versioned component-release schema; do not
//! fork generated protocol bindings by hand.

pub const SCHEMA: &str = "simplicio.component-release/v1";
pub const SCHEMA_SHA256: &str = "{digest}";
pub const REQUIRED_COMPONENTS: &[&str] = &["agent-contracts", "code", "loop-hub", "runtime"];

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ComponentRelease {{
    pub name: String,
    pub version: String,
    pub commit: String,
    pub protocol: String,
    pub artifact_digest: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_client_digest: Option<String>,
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    if tuple(REQUIRED) != ("agent-contracts", "code", "loop-hub", "runtime"):
        raise AssertionError("required component order changed")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(args.schema), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
