//! Minimal stdio JSON-RPC server standing in for a real Simplicio Runtime.
//!
//! Speaks just enough of the MCP subset `RuntimeClient` uses (`initialize`,
//! `notifications/initialized`, `tools/list`, `tools/call`) to exercise
//! `RuntimeClient::search`/`read_file`/`write_file`/`delete_file` end to end
//! without depending on a real Runtime binary being installed. Pointed to via
//! `SIMPLICIO_BIN` in `tests/fake_server_search.rs`.
//!
//! Deliberately tiny: one line of JSON in, one line of JSON out, matching
//! `RuntimeClient::request`'s framing (`serde_json::to_writer` + `\n`).
//!
//! `SIMPLICIO_FAKE_SERVER_MODE` (unset = normal) selects a misbehaving
//! handshake response, used by `tests/fake_server_malformed_handshake.rs` to
//! regression-test `RuntimeClient`'s fail-fast diagnostics without needing a
//! real broken Runtime binary:
//! - `banner_then_json`: replies to `initialize` with a non-JSON-RPC banner
//!   line instead of a response, simulating a misbehaving Runtime that prints
//!   startup noise on stdout before ever speaking JSON-RPC.
//! - `hang_handshake`: never replies to `initialize`, simulating a wedged
//!   Runtime process so the handshake timeout (not the normal I/O timeout)
//!   is what has to fire.
//! - `proptest_raw`: replies to `initialize` with the raw bytes decoded from
//!   `SIMPLICIO_FAKE_RAW_HANDSHAKE_BASE64` (base64, so arbitrary
//!   proptest-generated bytes survive the env var transport unmangled)
//!   instead of a well-formed response. Used by
//!   `tests/fake_server_handshake_proptest.rs` (code#67) to replay an
//!   arbitrary malformed/partial handshake response per property-test case
//!   without needing a real broken Runtime binary.

use std::io::{self, BufRead, Write};

use base64::Engine as _;
use serde_json::{Value, json};

fn main() {
    let mode = std::env::var("SIMPLICIO_FAKE_SERVER_MODE").unwrap_or_default();
    let stdin = io::stdin();
    let mut stdout = io::stdout();
    for line in stdin.lock().lines() {
        let Ok(line) = line else { break };
        if line.trim().is_empty() {
            continue;
        }
        let Ok(message) = serde_json::from_str::<Value>(&line) else {
            continue;
        };
        let method = message.get("method").and_then(Value::as_str).unwrap_or("");
        let id = message.get("id").cloned();

        if method == "initialize" && mode == "banner_then_json" {
            // Non-JSON-RPC noise on the same stream the client reads its
            // handshake response from, e.g. a startup banner printed before
            // the server is ready to speak the protocol.
            let _ = writeln!(stdout, "Simplicio Runtime booting, please wait...");
            let _ = stdout.flush();
            continue;
        }
        if method == "initialize" && mode == "hang_handshake" {
            // Never respond: the client's handshake-timeout watcher must
            // kill this process, not the caller's normal exec timeout.
            std::thread::sleep(std::time::Duration::from_secs(3600));
            continue;
        }
        if method == "initialize" && mode == "proptest_raw" {
            let encoded = std::env::var("SIMPLICIO_FAKE_RAW_HANDSHAKE_BASE64").unwrap_or_default();
            let raw = decode_base64(&encoded);
            let _ = stdout.write_all(&raw);
            if raw.last() != Some(&b'\n') {
                let _ = stdout.write_all(b"\n");
            }
            let _ = stdout.flush();
            continue;
        }

        match method {
            "initialize" => write_response(
                &mut stdout,
                id,
                json!({
                    "protocolVersion": "2024-11-05",
                    "serverInfo": { "name": "simplicio", "version": "fake-test-server" }
                }),
            ),
            "notifications/initialized" => {
                // Notifications carry no `id` and expect no response.
            }
            "tools/list" => write_response(
                &mut stdout,
                id,
                json!({
                    "tools": [
                        { "name": "simplicio_file_read" },
                        { "name": "simplicio_fs_write" },
                        { "name": "simplicio_fs_delete" },
                        { "name": "simplicio_search" },
                        { "name": "simplicio_fs_list" },
                        { "name": "simplicio_fs_stat" },
                        { "name": "simplicio_edit" },
                        { "name": "simplicio_exec" },
                    ]
                }),
            ),
            "tools/call" => {
                let name = message
                    .pointer("/params/name")
                    .and_then(Value::as_str)
                    .unwrap_or("");
                let arguments = message
                    .pointer("/params/arguments")
                    .cloned()
                    .unwrap_or_else(|| json!({}));
                write_response(&mut stdout, id, handle_tool_call(name, &arguments));
            }
            _ => {}
        }
    }
}

/// Builds the `tools/call` `result` object (`isError` + `content[].text`,
/// matching the shape `RuntimeClient::call_tool`/`tool_text` expect).
fn handle_tool_call(name: &str, arguments: &Value) -> Value {
    match name {
        "simplicio_search" => {
            let path = arguments.get("path").and_then(Value::as_str).unwrap_or("");
            let scope = if path.is_empty() { "." } else { path };
            let body = json!({
                "schema": "simplicio.search-result/v1",
                "matches": [
                    { "path": format!("{scope}/fake_match.rs"), "line": 1, "text": "fn fake_match() {}" }
                ],
                "truncated": false,
            });
            tool_ok(body.to_string())
        }
        "simplicio_fs_write" | "simplicio_fs_delete" => tool_ok("{}".to_owned()),
        "simplicio_fs_list" => tool_ok(json!({"schema":"simplicio.fs-list-result/v1","entries":[{"path":"src","kind":"directory"}],"truncated":false}).to_string()),
        "simplicio_fs_stat" => tool_ok(json!({"schema":"simplicio.fs-stat-result/v1","path":arguments.get("path").and_then(Value::as_str).unwrap_or(""),"kind":"file","size":12}).to_string()),
        "simplicio_edit" => {
            let plan = arguments
                .get("plan")
                .and_then(Value::as_str)
                .and_then(|plan| serde_json::from_str::<Value>(plan).ok())
                .unwrap_or(Value::Null);
            tool_ok(
                json!({
                    "schema": "simplicio.edit-result/v1",
                    "accepted": true,
                    "plan": plan,
                })
                .to_string(),
            )
        }
        "simplicio_file_read" => {
            let path = arguments.get("path").and_then(Value::as_str).unwrap_or("");
            let body = json!({
                "schema": "simplicio.read-result/v1",
                "path": path,
                "content": "fake content",
                "truncated": false,
            });
            tool_ok(body.to_string())
        }
        "simplicio_exec" => {
            let argv = arguments.get("argv").and_then(Value::as_array);
            if argv.and_then(|values| values.first()).and_then(Value::as_str) == Some("__fail__") {
                json!({"isError":true,"content":[{"type":"text","text":"injected exec failure"}]})
            } else {
                tool_ok(json!({"schema":"simplicio.exec-result/v1","exit_code":0,"stdout":"fake stdout","stderr":"","effect":"committed","idempotency_key":arguments.get("idempotency_key")}).to_string())
            }
        }
        other => json!({
            "isError": true,
            "content": [{ "type": "text", "text": format!("fake server: unknown tool '{other}'") }],
        }),
    }
}

fn tool_ok(text: String) -> Value {
    json!({
        "isError": false,
        "content": [{ "type": "text", "text": text }],
    })
}

/// Decodes a base64 payload used to transport arbitrary
/// proptest-generated bytes through `SIMPLICIO_FAKE_RAW_HANDSHAKE_BASE64`
/// (an env var, so raw bytes containing `NUL`/invalid-UTF-8/newlines would
/// not survive intact otherwise). Falls back to an empty payload on a
/// decode failure instead of panicking the fake server.
fn decode_base64(encoded: &str) -> Vec<u8> {
    base64::engine::general_purpose::STANDARD
        .decode(encoded)
        .unwrap_or_default()
}

fn write_response(stdout: &mut impl Write, id: Option<Value>, result: Value) {
    let response = json!({ "jsonrpc": "2.0", "id": id, "result": result });
    if serde_json::to_writer(&mut *stdout, &response).is_ok() {
        let _ = stdout.write_all(b"\n");
        let _ = stdout.flush();
    }
}
