//! Property test for code#67: for any malformed, partial, or
//! identity-mismatched handshake response the Runtime side could send,
//! `RuntimeClient::spawn_in` must always fail closed (return `Err`) — never
//! proceed with a broken/spoofed session, and never fall back to reading the
//! workspace directly off local disk (this client has no such fallback path
//! at all; this test is the guarantee that stays true as the handshake code
//! evolves).
//!
//! Extends the fake stdio server (`tests/support/fake_server_main.rs`) with a
//! `proptest_raw` mode that replays an arbitrary, proptest-generated raw byte
//! sequence as the `initialize` response instead of a well-formed one, via
//! `SIMPLICIO_FAKE_RAW_HANDSHAKE_BASE64` (base64-encoded so generated bytes —
//! including embedded newlines or invalid UTF-8 — survive the env var
//! transport unmangled).
//!
//! Six scenario families cover the malformed/partial space named in the
//! issue ("gerar respostas malformadas/parciais do handshake MCP"):
//!
//! 1. `non_json_noise`      — non-JSON-RPC bytes on the wire (startup banner-like).
//! 2. `missing_result`      — a valid JSON-RPC envelope with no `result` key at all.
//! 3. `protocol_error`      — a JSON-RPC `error` reply instead of a `result`.
//! 4. `missing_server_info` — `result` present, but no `serverInfo` object.
//! 5. `identity_mismatch`   — `serverInfo.name` present but not `"simplicio"`.
//! 6. `truncated_response`  — a byte-truncated prefix of an otherwise
//!    well-formed response (the literal "partial" case).
//!
//! Bounded to [`PROPTEST_CASES`] cases (well under proptest's default 256):
//! each case pays for a real subprocess spawn through `RuntimeClient::spawn_in`,
//! not a call into a pure function, so the usual default would make this
//! crate's test suite noticeably slower for marginal extra coverage on top
//! of the six scenario families already being fuzzed independently.
//!
//! Runs as its own integration-test binary/process (like the sibling
//! `fake_server_*.rs` files), so mutating `SIMPLICIO_BIN` /
//! `SIMPLICIO_FAKE_SERVER_MODE` / `SIMPLICIO_FAKE_RAW_HANDSHAKE_BASE64` here
//! cannot race a concurrent reader/writer of those same env vars elsewhere;
//! proptest itself runs cases for one `#[test]` fn sequentially within a
//! process, so the single-test-function invariant documented in
//! `fake_server_malformed_handshake.rs` holds here too.

use base64::Engine as _;
use proptest::prelude::*;
use serde_json::{Value, json};
use simplicio_runtime_client::RuntimeClient;

/// See the module doc comment for why this is far below proptest's default.
const PROPTEST_CASES: u32 = 48;

/// A `serverInfo.name` that is guaranteed not to match the expected
/// identity, case-insensitively, so scenario 5 always exercises the
/// identity-mismatch path (never accidentally passes the identity check).
fn non_simplicio_name() -> impl Strategy<Value = String> {
    "[a-zA-Z0-9_-]{0,24}".prop_filter("must not match the expected server identity", |s| {
        !s.eq_ignore_ascii_case("simplicio")
    })
}

/// One well-formed `initialize` response, used only as the truncation source
/// for scenario 6.
fn well_formed_initialize_response(id: u64) -> Value {
    json!({
        "jsonrpc": "2.0",
        "id": id,
        "result": {
            "protocolVersion": "2024-11-05",
            "serverInfo": { "name": "simplicio", "version": "fake-test-server" }
        }
    })
}

/// Builds one of the six malformed/partial handshake-response scenarios as a
/// raw line for the fake server to replay, alongside a short label used in
/// assertion-failure messages.
fn malformed_or_partial_handshake_response() -> impl Strategy<Value = (&'static str, String)> {
    prop_oneof![
        // 1. non-JSON noise on the wire (e.g. a startup banner), regression
        // sibling of `fake_server_malformed_handshake.rs`'s fixed example.
        "[ -~]{1,64}".prop_map(|noise| ("non_json_noise", format!("NOT-JSON: {noise}"))),
        // 2. valid JSON-RPC envelope, but no `result` key at all.
        any::<u64>().prop_map(|id| {
            (
                "missing_result",
                json!({ "jsonrpc": "2.0", "id": id }).to_string(),
            )
        }),
        // 3. a JSON-RPC protocol error instead of a result.
        (any::<u64>(), "[ -~]{0,32}").prop_map(|(id, message)| {
            (
                "protocol_error",
                json!({
                    "jsonrpc": "2.0", "id": id,
                    "error": { "code": -32000, "message": message }
                })
                .to_string(),
            )
        }),
        // 4. `result` present, but no `serverInfo` at all.
        any::<u64>().prop_map(|id| {
            (
                "missing_server_info",
                json!({
                    "jsonrpc": "2.0", "id": id,
                    "result": { "protocolVersion": "2024-11-05" }
                })
                .to_string(),
            )
        }),
        // 5. `serverInfo.name` present but not the expected identity.
        (any::<u64>(), non_simplicio_name()).prop_map(|(id, name)| {
            (
                "identity_mismatch",
                json!({
                    "jsonrpc": "2.0", "id": id,
                    "result": {
                        "protocolVersion": "2024-11-05",
                        "serverInfo": { "name": name }
                    }
                })
                .to_string(),
            )
        }),
        // 6. a byte-truncated prefix of an otherwise well-formed response
        // (the literal "partial handshake" scenario). `salt` is reduced
        // modulo the response length so the cut point always lands strictly
        // inside the string; the response is pure ASCII, so every byte
        // offset is a valid UTF-8 char boundary.
        (any::<u64>(), 0usize..10_000usize).prop_map(|(id, salt)| {
            let full = well_formed_initialize_response(id).to_string();
            let bound = full.len().max(1);
            let cut = (salt % bound).min(full.len().saturating_sub(1));
            ("truncated_response", full[..cut].to_string())
        }),
    ]
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(PROPTEST_CASES))]

    #[test]
    fn handshake_always_fails_closed_on_malformed_or_partial_responses(
        (label, raw_response) in malformed_or_partial_handshake_response(),
    ) {
        let fake_server = env!("CARGO_BIN_EXE_simplicio-fake-runtime-server");
        let repo = tempfile::tempdir().unwrap();
        let encoded = base64::engine::general_purpose::STANDARD.encode(raw_response.as_bytes());

        // SAFETY: see module doc comment — proptest runs cases for this
        // `#[test]` fn sequentially within this process, and no other test
        // in this integration-test binary touches these env vars.
        unsafe {
            std::env::set_var("SIMPLICIO_BIN", fake_server);
            std::env::set_var("SIMPLICIO_FAKE_SERVER_MODE", "proptest_raw");
            std::env::set_var("SIMPLICIO_FAKE_RAW_HANDSHAKE_BASE64", &encoded);
        }
        let result = RuntimeClient::spawn_in(repo.path());
        unsafe {
            std::env::remove_var("SIMPLICIO_FAKE_RAW_HANDSHAKE_BASE64");
            std::env::remove_var("SIMPLICIO_FAKE_SERVER_MODE");
            std::env::remove_var("SIMPLICIO_BIN");
        }

        prop_assert!(
            result.is_err(),
            "scenario '{label}' with raw response {raw_response:?} must fail closed (RuntimeClient has no local-disk fallback to fall back to), got Ok(_)"
        );
    }
}
