//! DO NOT EDIT: generated by `scripts/release/generate_component_client.py`.
//!
//! Regenerate this file from the versioned component-release schema; do not
//! fork generated protocol bindings by hand.

pub const SCHEMA: &str = "simplicio.component-release/v1";
pub const SCHEMA_SHA256: &str = "a1e967982e9ffa6a8eff827a3d1329d90fc56fa1ea285fa25862763b0694dc82";
pub const REQUIRED_COMPONENTS: &[&str] = &["agent-contracts", "code", "loop-hub", "runtime"];

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ComponentRelease {
    pub name: String,
    pub version: String,
    pub commit: String,
    pub protocol: String,
    pub artifact_digest: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_client_digest: Option<String>,
}
