//! DO NOT EDIT: generated by `scripts/release/generate_component_client.py`.
//!
//! Regenerate this file from the versioned component-release schema; do not
//! fork generated protocol bindings by hand.

pub const SCHEMA: &str = "simplicio.component-release/v1";
pub const SCHEMA_SHA256: &str = "1c904fa03ed6a7c3d9a25f74b719616b9b1fbecff0636eb704b3e2bfef1cf093";
pub const REQUIRED_COMPONENTS: &[&str] = &["agent-contracts", "code", "loop-hub", "runtime"];

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ComponentRelease {
    pub name: String,
    pub version: String,
    pub commit: String,
    pub protocol: String,
    pub artifact_digest: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generated_client_digest: Option<String>,
}
